### ISSUE TITLE
ERROR  no module 'dotenv'

### ISSUE THREAD

**Issue by vladosnos** [fecton/assbot#3]
C:\assbot-main>loader.py
Traceback (most recent call last):
  File "C:\assbot-main\loader.py", line 5, in <module>
    from data.config import TOKEN, DB_NAME
  File "C:\assbot-main\data\config.py", line 2, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

C:\assbot-main>

**Comment by fecton** [comment]
# :D
```
pip3 install python-dotenv
```
