### ISSUE TITLE
Traceback (most recent call last):   File "C:\assbot-main\loader.py", line 5, in <module>     from data.config import TOKEN, DB_NAME   File "C:\assbot-main\data\config.py", line 9, in <module>     SUPER_USERS = [int(getenv("1136703023"))]  # админы TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by vladosnos** [fecton/assbot#4]
Traceback (most recent call last):
  File "C:\assbot-main\loader.py", line 5, in <module>
    from data.config import TOKEN, DB_NAME
  File "C:\assbot-main\data\config.py", line 9, in <module>
    SUPER_USERS = [int(getenv("1136703023"))]  # админы
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by vladosnos** [comment]
как исправить?
